/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_pipe.c                                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: smorlier <smorlier@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/12/10 10:40:57 by smorlier          #+#    #+#             */
/*   Updated: 2025/12/10 11:48:30 by smorlier         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>

void	fail_on(char *str)
{
	perror(str);
	exit(EXIT_FAILURE);
}
void	child_process(int *pipefd)
{
	char	buf;
	int		ret;

	write(STDOUT_FILENO, "start child process\n", 21);
	close(pipefd[1]);
	ret = 1;
	while (ret > 0)
	{
		ret = read(pipefd[0], &buf, 1);
		if (ret > 0)
			write(STDOUT_FILENO, &buf, 1);
	}
	close(pipefd[0]);
	if (ret < 0)
		fail_on("read");
	write(STDOUT_FILENO, "\n", 1);
	write(STDOUT_FILENO, "end of child process\n", 21);
	exit(EXIT_SUCCESS);
}

void	parent_process(int *pipefd, char *str)
{
	int	ret;

	close(pipefd[0]);
	write(STDOUT_FILENO, "start parent job\n", 18);
	while (*str)
	{
		ret = write(pipefd[1], str, 1);
		if (ret < 0)
			fail_on("write");
		str++;
	}
	close(pipefd[1]);
	write(STDOUT_FILENO, "end of parent job\n", 19);
	return ;
}

int	ft_pipe(char *str)
{
	int		pipefd[2];
	pid_t	pid;

	if (pipe(pipefd) < 0)
		fail_on("pipe");
	pid = fork();
	if (pid < 0)
		fail_on("fork");
	if (pid == 0)
		child_process(pipefd);
	else
		parent_process(pipefd, str);
	wait(NULL);
	write(STDOUT_FILENO, "end of ft_pipe\n", 16);
	return (EXIT_SUCCESS);
}

int	main(void)
{
	int	ret;
	
	ret = ft_pipe("STR GENERATED BY PARENT, WRITTEN BY CHILD");
	return (ret);
}